# 配置备份路径
config_path = "/data/network/config/"

#日志记录路径
log_path = "/var/log/network.log"

#并发线程数
max_workers = 10

#企业微信配置
[webhook]
enable = false #默认fasle不发送企业微信通知,为true则发送
url = "" #企业微信机器人webhook地址

#邮件配置
[mail]
enable = true #默认发送邮件
server = "" # 邮件服务器地址 smtp.xxx.com
port = 25 #实际修改
from_addr = "" #发件人邮箱
to_addr = "" #多个收件人邮箱逗号隔开
password = "" #发件人密码

#scp配置
#该配置用于checkpoint防火墙备份核心配置用,如无checkpoint防火墙,则忽略.
#建议使用部署服务本机作为scp,scp将拷贝配置文件到config_path定义的备份路径下
[scp]
host = ""
user = ""
pass = ""

#设备信息
############################################################################
# 支持web api设备command可为空,如:飞塔/山石/checkpoint/poloalto防火墙等        #
#                                                                          #
############################################################################

[[devices]]
host = "1.1.1.1"
vendor = "cisco_ios" #思科IOS设备
command = "show run"
username = "root"
password = "password"
port = "22"

[[devices]]
host = "1.1.1.2"
vendor = "huawei" #华为设备
command = "display cu"
username = "root"
password = "password"
port = "22"

[[devices]]
host = "1.1.1.3"
vendor = "hp_comware" #H3C华三设备
command = "display cu"
username = "root"
password = "password"
port = "22"

[[devices]]
host = "1.1.1.4"
vendor = "cisco_nxos" #思科DC NX交换机
command = "show run"
username = "root"
password = "password"
port = "22"

[[devices]]
host = "1.1.1.5"
vendor = "cisco_asa" #思科防火墙
command = "show run"
username = "root"
password = "password"
port = "22"

[[devices]]
host = "1.1.1.6"
vendor = "fortigate" #飞塔防火墙
command = ""
username = "root"
password = "password"
port = "8443"

[[devices]]
host = "1.1.1.7"
vendor = "juniper_junos" # junos设备
command = "show configuration"
username = "root"
password = "password"
port = "22"

[[devices]]
host = "1.1.1.8"
vendor = "juniper_junos" # junos设备
command = "show configuration"
username = "root"
password = "password"
port = "22"

[[devices]]
host = "1.1.1.9"
vendor = "cisco_ios" #思科IOS设备
command = "show run"
username = "root"
password = "password"
port = "22"

[[devices]]
host = "1.1.1.10"
vendor = "hillstone" #山石防火墙
command = ""
username = "root"
password = "password"
port = "443"

[[devices]]
host = "1.1.1.11"
vendor = "checkpoint" #cp防火墙
command = ""
username = "root"
password = "password"
expert_password = "expert_password" #进入专家模式密码
port = "22"